services:
  idempiere:
    image: openhmis/banda-idempiere:${IDEMPIERE_VERSION}
    depends_on:
      - postgres
    volumes:
      - ./src:/home/src
    environment:
      - DB_ADMIN_PASS=${POSTGRES_PASSWORD}
      - DB_HOST=${POSTGRES_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${IDEMPIERE_DATABASE_PASSWORD}
      - DB_PORT=${POSTGRES_PORT}
      - IDEMPIERE_FRESH_DB=${IDEMPIERE_FRESH_DB}
      - IDEMPIERE_VERSION=${IDEMPIERE_VERSION}
      - MIGRATE_EXISTING_DATABASE=${MIGRATE_EXISTING_DATABASE}
      - GENERATE_PLUGIN_BUNDLE_INFO=${GENERATE_PLUGIN_BUNDLE_INFO}
      - HEALTHY_AFTER_PLUGINS_START=${HEALTHY_AFTER_PLUGINS_START}
    ports:
      - ${IDEMPIERE_PORT}:8080
      - ${IDEMPIERE_SSL_PORT}:8443
      - ${TELNET_PORT}:12612

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}