services:
  idempiere:
    image: openhmis/banda-idempiere:${IDEMPIERE_VERSION}
    depends_on:
      - postgres
    volumes:
      - ./src:/home/src
    environment:
      - CI=${CI}
      - DB_ADMIN_PASS=${POSTGRES_PASSWORD}
      - DB_HOST=${POSTGRES_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${IDEMPIERE_DATABASE_PASSWORD}
      - DB_PORT=${POSTGRES_PORT}
      - IDEMPIERE_FRESH_DB=${IDEMPIERE_FRESH_DB}
      - IDEMPIERE_VERSION=${IDEMPIERE_VERSION}
      - MIGRATE_EXISTING_DATABASE=${MIGRATE_EXISTING_DATABASE}
    ports:
      - ${IDEMPIERE_PORT}:8080
      - ${IDEMPIERE_SSL_PORT}:8443
      - ${TELNET_PORT}:12612
    healthcheck:
      test: "[ ! -f \"/opt/idempiere/.unhealthy\" ] && exit 0 || exit 1"
      interval: 1s
      timeout: 1s
      retries: 600
      start_period: 5s

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432