version: '3.8'

services:
  idempiere:
    build: .
    depends_on:
      - postgres
    volumes:
      - migration:/opt/idempiere/banda-migration
    environment:
      - DB_ADMIN_PASS=${POSTGRES_PASSWORD}
      - DB_PORT=${POSTGRES_PORT}
      - DB_PASS=${IDEMPIERE_DATABASE_PASSWORD}
    ports:
      - ${IDEMPIERE_PORT}:8080
      - 8443:8443
      - 12612:12612

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  migration: