version: '3.8'

services:
  idempiere:
    build: .
    depends_on:
      - postgres
    volumes:
      - ./src:/home/src
      - ./docker-entrypoint.sh:/opt/idempiere/docker-entrypoint.sh
    environment:
      - DB_ADMIN_PASS=${POSTGRES_PASSWORD}
      - DB_PASS=${IDEMPIERE_DATABASE_PASSWORD}
      - IDEMPIERE_FRESH_DB=${IDEMPIERE_FRESH_DB}
      - MIGRATE_EXISTING_DATABASE=${MIGRATE_EXISTING_DATABASE}
      - EXPORT_DB=${EXPORT_DB}
    ports:
      - ${IDEMPIERE_PORT}:8080
      - ${IDEMPIERE_SSL_PORT}:8443
      - ${TELNET_PORT}:12612
    healthcheck:
      test: "[ ! -f \".unhealthy\" ] && exit 0 || exit 1"
      interval: 1s
      timeout: 1s
      retries: 600
      start_period: 5s

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432